[package]
name = "photosort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
string-builder = "0.2.0" # A simple string builder type
symlink = "0.1.0" # Cross-platform symlink
serde = { version = "1.0.143", features = ["derive"] } # Serialization & deserialization

[dev-dependencies]
uuid = { version = "1.1.2", features = ["v4"] }
