[package]
name = "photosort"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true  # Automatically strip symbols from the binary.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
env_logger = "0.9"
symlink = "0.1.0" # Cross-platform symlink
serde = { version = "1.0.143", features = ["derive"] } # Serialization & deserialization
thiserror = "1.0"
notify = "5.0"

[dev-dependencies]
uuid = { version = "1.1.2", features = ["v4"] }
